/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    regions: Region;
    locations: Location;
    factions: Faction;
    npcs: Npc;
    items: Item;
    deities: Deity;
    characters: Character;
    sessions: Session;
    quests: Quest;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    factions: FactionsSelect<false> | FactionsSelect<true>;
    npcs: NpcsSelect<false> | NpcsSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    deities: DeitiesSelect<false> | DeitiesSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    quests: QuestsSelect<false> | QuestsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    campaign: Campaign;
  };
  globalsSelect: {
    campaign: CampaignSelect<false> | CampaignSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Optional folio byline override.
   */
  displayLabel?: string | null;
  role: 'admin' | 'player';
  /**
   * Player's character (leave empty for admins).
   */
  pc?: (number | null) | Character;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  name: string;
  /**
   * Owning user; only that user (or admin) can edit this PC.
   */
  player?: (number | null) | User;
  playerLabel?: string | null;
  class: string;
  subclass?: string | null;
  level?: number | null;
  race?: string | null;
  quote?: string | null;
  vitals?: {
    hpCurrent?: number | null;
    hpMax?: number | null;
    ac?: number | null;
  };
  stats?: {
    STR?: number | null;
    DEX?: number | null;
    CON?: number | null;
    INT?: number | null;
    WIS?: number | null;
    CHA?: number | null;
  };
  accentHue?: number | null;
  backstory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gear?:
    | {
        name: string;
        item?: (number | null) | Item;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  portrait?: (number | null) | Media;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  name: string;
  kind?: string | null;
  rarity?: ('Common' | 'Uncommon' | 'Rare' | 'Very rare' | 'Legendary' | 'Unknown') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ownerCharacter?: (number | null) | Character;
  ownerFaction?: (number | null) | Faction;
  ownerNpc?: (number | null) | Npc;
  /**
   * Display fallback when no relation is set
   */
  ownerLabel?: string | null;
  portrait?: (number | null) | Media;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factions".
 */
export interface Faction {
  id: number;
  name: string;
  tone: 'Ally' | 'Antagonist' | 'Neutral' | 'Historical' | 'Mystery';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seatLocation?: (number | null) | Location;
  relatedFactions?: (number | Faction)[] | null;
  portrait?: (number | null) | Media;
  accentHue?: number | null;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  region: number | Region;
  kind: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mapPosition?: {
    x?: number | null;
    y?: number | null;
  };
  relatedNpcs?: (number | Npc)[] | null;
  relatedFactions?: (number | Faction)[] | null;
  portrait?: (number | null) | Media;
  accentHue?: number | null;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  area: 'North' | 'Centre' | 'South' | 'Islands';
  kind: string;
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mapPosition?: {
    x?: number | null;
    y?: number | null;
  };
  accentHue?: number | null;
  portrait?: (number | null) | Media;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "npcs".
 */
export interface Npc {
  id: number;
  name: string;
  title?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  currentLocation?: (number | null) | Location;
  currentLocationLabel?: string | null;
  factions?: (number | Faction)[] | null;
  regions?: (number | Region)[] | null;
  status?: ('alive' | 'missing' | 'imprisoned' | 'dead' | 'unknown') | null;
  portrait?: (number | null) | Media;
  accentHue?: number | null;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deities".
 */
export interface Deity {
  id: number;
  name: string;
  tier: 'Primordial' | 'Greater' | 'Lesser' | 'Dark';
  domain?: string | null;
  status?: ('withdrawn' | 'silent' | 'alive' | 'rising' | 'exiled' | 'dead') | null;
  lastSeen?: string | null;
  lastSeenLocation?: (number | null) | Location;
  symbol?: string | null;
  alignment?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  accentHue?: number | null;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  title: string;
  number: number;
  inWorldDate?: string | null;
  realDate?: string | null;
  author: number | User;
  /**
   * In-world byline; may differ from the user account.
   */
  authorLabel?: string | null;
  /**
   * The opening line — used as the dropcap.
   */
  excerpt?: string | null;
  /**
   * The folio body.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A note in the warmer hand, added later.
   */
  marginalia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedEntities?:
    | (
        | {
            relationTo: 'npcs';
            value: number | Npc;
          }
        | {
            relationTo: 'locations';
            value: number | Location;
          }
        | {
            relationTo: 'factions';
            value: number | Faction;
          }
        | {
            relationTo: 'deities';
            value: number | Deity;
          }
        | {
            relationTo: 'items';
            value: number | Item;
          }
      )[]
    | null;
  lastAmendedBy?: (number | null) | User;
  lastAmendedByLabel?: string | null;
  lastAmendedAt?: string | null;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests".
 */
export interface Quest {
  id: number;
  title: string;
  status: 'active' | 'open' | 'complete';
  priority: 'main' | 'side' | 'mystery';
  summary?: string | null;
  steps?:
    | {
        text: string;
        done?: boolean | null;
        id?: string | null;
      }[]
    | null;
  relatedNpcs?: (number | Npc)[] | null;
  relatedLocations?: (number | Location)[] | null;
  relatedFactions?: (number | Faction)[] | null;
  linkedSession?: (number | null) | Session;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  title: string;
  body?: string | null;
  status: 'open' | 'following' | 'resolved' | 'dead-end';
  /**
   * Auto-set on create from the logged-in user.
   */
  author?: (number | null) | User;
  authorLabel?: string | null;
  linkedSession?: (number | null) | Session;
  notes?:
    | {
        author?: (number | null) | User;
        authorLabel?: string | null;
        text: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated from name; edit only if you know what you are doing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'factions';
        value: number | Faction;
      } | null)
    | ({
        relationTo: 'npcs';
        value: number | Npc;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'deities';
        value: number | Deity;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'quests';
        value: number | Quest;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  displayLabel?: T;
  role?: T;
  pc?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  area?: T;
  kind?: T;
  tagline?: T;
  description?: T;
  mapPosition?:
    | T
    | {
        x?: T;
        y?: T;
      };
  accentHue?: T;
  portrait?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  region?: T;
  kind?: T;
  description?: T;
  mapPosition?:
    | T
    | {
        x?: T;
        y?: T;
      };
  relatedNpcs?: T;
  relatedFactions?: T;
  portrait?: T;
  accentHue?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factions_select".
 */
export interface FactionsSelect<T extends boolean = true> {
  name?: T;
  tone?: T;
  description?: T;
  seatLocation?: T;
  relatedFactions?: T;
  portrait?: T;
  accentHue?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "npcs_select".
 */
export interface NpcsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  bio?: T;
  currentLocation?: T;
  currentLocationLabel?: T;
  factions?: T;
  regions?: T;
  status?: T;
  portrait?: T;
  accentHue?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  rarity?: T;
  description?: T;
  ownerCharacter?: T;
  ownerFaction?: T;
  ownerNpc?: T;
  ownerLabel?: T;
  portrait?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deities_select".
 */
export interface DeitiesSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  domain?: T;
  status?: T;
  lastSeen?: T;
  lastSeenLocation?: T;
  symbol?: T;
  alignment?: T;
  description?: T;
  accentHue?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  name?: T;
  player?: T;
  playerLabel?: T;
  class?: T;
  subclass?: T;
  level?: T;
  race?: T;
  quote?: T;
  vitals?:
    | T
    | {
        hpCurrent?: T;
        hpMax?: T;
        ac?: T;
      };
  stats?:
    | T
    | {
        STR?: T;
        DEX?: T;
        CON?: T;
        INT?: T;
        WIS?: T;
        CHA?: T;
      };
  accentHue?: T;
  backstory?: T;
  gear?:
    | T
    | {
        name?: T;
        item?: T;
        description?: T;
        id?: T;
      };
  portrait?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  title?: T;
  number?: T;
  inWorldDate?: T;
  realDate?: T;
  author?: T;
  authorLabel?: T;
  excerpt?: T;
  body?: T;
  marginalia?: T;
  relatedEntities?: T;
  lastAmendedBy?: T;
  lastAmendedByLabel?: T;
  lastAmendedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests_select".
 */
export interface QuestsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  priority?: T;
  summary?: T;
  steps?:
    | T
    | {
        text?: T;
        done?: T;
        id?: T;
      };
  relatedNpcs?: T;
  relatedLocations?: T;
  relatedFactions?: T;
  linkedSession?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  status?: T;
  author?: T;
  authorLabel?: T;
  linkedSession?: T;
  notes?:
    | T
    | {
        author?: T;
        authorLabel?: T;
        text?: T;
        createdAt?: T;
        id?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign".
 */
export interface Campaign {
  id: number;
  name?: string | null;
  tagline?: string | null;
  /**
   * Citation rendered under the tagline.
   */
  tagSource?: string | null;
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  currentSession?: number | null;
  partyName?: string | null;
  partyLevel?: number | null;
  partyXp?: number | null;
  nextLevelXp?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign_select".
 */
export interface CampaignSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  tagSource?: T;
  summary?: T;
  currentSession?: T;
  partyName?: T;
  partyLevel?: T;
  partyXp?: T;
  nextLevelXp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}